-- ============================================================
-- Supabase Schema for Blood Donor Registry
-- Run this in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/djbzmvcctcjnomaqathc/sql/new
-- ============================================================

create table if not exists public.blood_donors (
  id bigint generated by default as identity primary key,
  sl_no integer,
  name text not null,
  blood_group text not null,
  contact_email text,
  mobile_number text not null unique,
  address text,
  pin_code text,
  consent text,
  is_verified boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.blood_donors enable row level security;

-- 1. Allow public read access (for search / stats on website)
create policy "Allow public read access"
on public.blood_donors
for select
to anon, authenticated
using (true);

-- 2. Allow public inserts (from website registration / forms) with basic validation
create policy "Allow insert access"
on public.blood_donors
for insert
to anon, authenticated
with check (
  char_length(trim(name)) > 0 
  and char_length(trim(mobile_number)) >= 10
  and blood_group in ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')
);

-- 3. Restrict updates and deletes to authenticated admins only (prevents unauthorized public tampering)
create policy "Allow authenticated admin update"
on public.blood_donors
for update
to authenticated
using (true);

create policy "Allow authenticated admin delete"
on public.blood_donors
for delete
to authenticated
using (true);
